<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class SanPhamSeeder extends Seeder
{
    public function run()
    {
        DB::table('san_phams')->delete();

        DB::table('san_phams')->truncate();

        DB::table('san_phams')->insert([
            [
                'ten_san_pham'            => 'Áo Thun Nam Tay Ngắn In Chữ Sarah Baker',
                'slug_san_pham'           => Str::slug('Áo Thun Nam Tay Ngắn In Chữ Sarah Baker'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211ATA4132505/4e3380e5-791e-4336-9b75-94287012d044.jpg',
                'mo_ta'                   => '- Tên sản phẩm: Áo Thun Nam Tay Ngắn In Chữ Sarah Baker
                                                - Độ tuổi: > 13 tuổi
                                                - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Nam Tay Ngắn In Chữ Werby Nhed',
                'slug_san_pham'           => Str::slug('Áo Thun Nam Tay Ngắn In Chữ Werby Nhed'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209ATA0671701/3af609f0-8ab6-4d4d-b489-464374f92db2.jpg',
                'mo_ta'                   => '- Tên sản phẩm: Áo Thun Nam Tay Ngắn In Chữ Sarah Baker
                                            - Độ tuổi: > 13 tuổi
                                            - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 189000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Chữ Greative',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Chữ Greative'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATA0670901/3dedbe52-ed87-47fd-a019-f447b7047092.jpg',
                'mo_ta'                   => ' - Tên sản phẩm: Áo Thun Tay Ngắn In Chữ GREATIVE
                                            - Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.
                                            - Chất liệu: Vải thun',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '8',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Polo Nam Phối Màu Túi',
                'slug_san_pham'           => Str::slug('Áo Polo Nam Phối Màu Túi'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIwNjI5MDA3MC8xOTNiMzI2ZC05ZjdmLTQ4ZmItODBhYi1jNThlMWI2YWQ2YzFfMDlDOTY5RTJCQjNCMzdBNTIwQUNENzhENDUwNDE5QjcuanBn0',
                'mo_ta'                   => 'Áo polo là item được nhiều người chọn làm phong cách thời trang riêng bởi độ lịch lãm, thoải mái mà món đồ này mang lại. Đồng thời áo polo còn dễ dàng mix với nhiều món đồ',
                'gia_ban'                 => 275000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Nam Phối Màu Cổ Và Tay',
                'slug_san_pham'           => Str::slug('Áo Polo Nam Phối Màu Cổ Và Tay'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/el-finder-file-system/thumb/v1_L3Byb2R1Y3RzLzIzMDFQVEFGTUYxMDAxL2YyMzVlNTEzLTcxNjUtNDU4NC1iN2RkLTYwYWM2ZjZjZDYxZF80QkFCQzRCQUZERDcxRjBBNjFBMjA2NUE0NURGMEE2RC5qcGc1',
                    'mo_ta'               => '- Tên sản phẩm: Áo Polo Nam Phối Màu Cổ Và Tay
                                              - Độ tuổi: > 14 tuổi
                                            - Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 269000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Nam In Hình Mặt Cười',
                'slug_san_pham'           => Str::slug('Áo Polo Nam In Hình Mặt Cười'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207ATA5360401/2afd93c4-b593-4d52-8744-2ca0475cb455.jpg',
                'mo_ta'                   => 'Áo polo là item được nhiều phái mạnh chọn làm phong cách thời trang riêng bởi độ lịch lãm, thoải mái mà món đồ này mang lại.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '9',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sơ Mi Nam Tay Ngắn Giấu Túi',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nam Tay Ngắn Giấu Túi'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211ASAFMF0801/0c559e26-11d2-4a6b-aca4-6827e44d25fa.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Nam Tay Ngắn Túi Nắp',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nam Tay Ngắn Túi Nắp'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211ASAFMF2601/0ebb9dbd-58b9-4a48-92c6-eccde61cc75a.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Sơ Mi Nam Tay Dài Sọc',
                'slug_san_pham'           => Str::slug('Sơ Mi Nam Tay Dài Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2204ASAFMF0401/5392170a-158f-4a97-aab8-992dbad67d3b.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 249000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '10',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Jeans Nam Đen Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Đen Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210QJA8052302/ee968914-f10a-43a3-add4-fe216b81b850.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209QJA5171901/05c0f69c-0615-464d-b9b4-0f9d6d88c9de.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 395000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209QJA8051701/6dd56ff9-df91-46e9-b62c-fd49708b6c47.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 345000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '11',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Kaki Nam Dài Trơn',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Dài Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210QKA9400701/5d369092-9ad0-462e-8155-06969ae63fc7.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 325000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Kaki Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2208QKA9151801/316f3afe-08b1-4624-a762-1c85b06c097b.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 325000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Kaki Nam Dài Mac Fm',
                'slug_san_pham'           => Str::slug('Quần Kaki Nam Dài Mac Fm'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209QKA8380701/16abbb68-1cb1-43bd-a1cf-72152c8aad13.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 295000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '12',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Short Kaki Nam Trơn',
                'slug_san_pham'           => Str::slug('Quần Short Kaki Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2205SKA9151901/4e89e229-f9a8-4069-90c8-fff665e364e9.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 175000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Short Tổ Ong Lưng Thun 2 Túi Hộp',
                'slug_san_pham'           => Str::slug('Quần Short Tổ Ong Lưng Thun 2 Túi Hộp'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207STA9152901/2e40e19d-5841-44e7-981e-e986762c010f.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Short Đũi Lưng Thun Rút Dây',
                'slug_san_pham'           => Str::slug('Quần Short Đũi Lưng Thun Rút Dây'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209SKA9151301/3a4fee8d-f03e-48c3-a7b6-1a8fe1725d73.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi chơi, ở nhà',
                'gia_ban'                 => 129000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '13',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Feel No Toks',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Feel No Toks'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211KKAFMF0503/a0cb0b3f-7f53-426e-8b47-21182278bb62.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Bomber Nam Trơn',
                'slug_san_pham'           => Str::slug('Áo Khoác Bomber Nam Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211KKAFMF3002/827ae86e-8568-4454-beac-a356de61bc61.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 395000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Gió Nam Phối Sọc',
                'slug_san_pham'           => Str::slug('Áo Khoác Gió Nam Phối Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212KKAFMF0201/36555c9e-90f8-417d-9974-66d158c3c195.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc khoác quanh năm.',
                'gia_ban'                 => 475000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '14',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Feel No Toks',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Feel No Toks'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ARA5641902/0f412df4-7d6a-491e-8844-e5528989d540.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sweater Nam Thêu Chữ Goff',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam Thêu Chữ Goff'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ARA5642102/cba71db4-c42e-4a25-af4e-1e84c4a6bb0f.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sweater Nam In Chữ Atpseafm',
                'slug_san_pham'           => Str::slug('Áo Sweater Nam In Chữ Atpseafm'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ARA5642805/420819e8-e314-4686-a6f3-898f84c579ed.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 355000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '15',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài 2 Sọc Ngang',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài 2 Sọc Ngang'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ALA9622601/6c35cae2-5056-4405-bab4-627e9e75fbbd.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài Cổ Tròn 2 Sọc',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài Cổ Tròn 2 Sọc'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ALA9622603/ba8c5632-3f4d-4b65-b817-deec2781c31d.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Len Nam Tay Dài Phối Màu',
                'slug_san_pham'           => Str::slug('Áo Len Nam Tay Dài Phối Màu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210ALA9622902/5b242664-b92d-4b76-a2d3-df0c4d34db24.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 375000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '16',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Polo Đôi Phối Màu Bo',
                'slug_san_pham'           => Str::slug('Áo Polo Đôi Phối Màu Bo'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATC0671504/10cd194e-51cb-49c6-b255-45d548fab3ea.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 285000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Polo Đôi Phối 2 Màu',
                'slug_san_pham'           => Str::slug('Áo Polo Đôi Phối 2 Màu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211ATC0671901/f529aba3-5e41-4691-a1d7-c48c2371fcaa.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 285000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Khoác Gió Có Mũ Nam Nữ',
                'slug_san_pham'           => Str::slug('Áo Khoác Gió Có Mũ Nam Nữ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209KKC4584581901/14d2a5b1-1194-4347-9f5d-7039631e48db.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 249000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '17',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Croptop In Hình Con Gái',
                'slug_san_pham'           => Str::slug('Áo Thun Croptop In Hình Con Gái'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATC5362703/53ecf6b8-7e35-4003-8b09-68e2adaa244b.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Gấu Hồng Lotso',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Gấu Hồng Lotso'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATC5362701/c496c5a6-8b23-4876-b8f1-0206fa676c3c.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 169000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Tay Ngắn In Chữ Lucky Happy',
                'slug_san_pham'           => Str::slug('Áo Thun Tay Ngắn In Chữ Lucky Happy'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ATC5362401/8f8930af-189d-49f1-9ce9-c18cdeb1917d.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi học, đi chơi, ở nhà.',
                'gia_ban'                 => 189000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '18',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Váy Thiết Kế Dáng Xoè Cổ Khoét',
                'slug_san_pham'           => Str::slug('Váy Thiết Kế Dáng Xoè Cổ Khoét'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2206VDUFMF1301/0bd31d73-a2bc-4d80-a9e9-e91bc50a341c.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 345000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Thiết Kế Cổ Chéo Cách Điệu',
                'slug_san_pham'           => Str::slug('Váy Thiết Kế Cổ Chéo Cách Điệu'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2206VDUFMF2202/25e06fd4-d8b5-46fe-a149-e7fa9b1d76d1.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 319000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Thiết Kế Cổ Yếm Khoét Ngực',
                'slug_san_pham'           => Str::slug('Váy Thiết Kế Cổ Yếm Khoét Ngực'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212VDUFMF1901/4e7292db-e401-4b30-856a-6b085af62b39.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 349000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '19',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Váy 2 Dây Xẻ Tà Vạt Trước',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Xẻ Tà Vạt Trước'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207VDUFMF0603/86522d10-f4f4-4ade-9d14-8ea47b944101.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 315000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy 2 Dây Dáng Dài Xẻ Tà',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Dáng Dài Xẻ Tà'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207VDUFMF3002/1e61503b-f6f9-41a5-8ec0-cc26cd7b433b.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy 2 Dây Bên Tà Chéo Xếp Ly Dưới',
                'slug_san_pham'           => Str::slug('Váy 2 Dây Bên Tà Chéo Xếp Ly Dưới'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2208VDUFMF0302/034fd1a7-5fc0-4b96-8f0e-7ce7068081f2.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi làm, đi chơi, dự tiệc.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '20',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Cổ Sen Đính Nút',
                'slug_san_pham'           => Str::slug('Váy Polo Cổ Sen Đính Nút'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301VDU5360701/129035fb-e460-4c2b-b0b2-fed74b3c2234.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 185000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Nữ Phối Màu Ngực',
                'slug_san_pham'           => Str::slug('Váy Polo Nữ Phối Màu Ngực'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301VDUFMF1701/060fca62-7f6f-44cf-bd62-fb7028173e02.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 229000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Váy Polo Dáng Chữ A 3 Nút',
                'slug_san_pham'           => Str::slug('Váy Polo Dáng Chữ A 3 Nút'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301VDUFMF0501/13177e05-11f8-492f-ae67-b9367d22a58c.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi, ở nhà.',
                'gia_ban'                 => 335000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '21',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Thun Nữ Tay Ngắn Bông Hoa',
                'slug_san_pham'           => Str::slug('Áo Thun Nữ Tay Ngắn Bông Hoa'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301ATU5361004/60246b21-b769-4cfa-9cde-900d324e6201.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Nữ Tay Ngắn In Chữ M',
                'slug_san_pham'           => Str::slug('Áo Thun Nữ Tay Ngắn In Chữ M'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301ATU5361002/1f800140-bb83-47a7-93fe-7edc607ba634.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Thun Nữ Tay Ngắn In Chữ You Are Loved',
                'slug_san_pham'           => Str::slug('Áo Thun Nữ Tay Ngắn In Chữ You Are Loved'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301ATU5361003/13f02ac7-bcdc-49ec-a99f-c590d28a7feb.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '22',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Sơ Mi Nữ Tay Ngắn Cổ Vest Màu Trơn',
                'slug_san_pham'           => Str::slug('Sơ Mi Nữ Tay Ngắn Cổ Vest Màu Trơn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2207ASUFMF2801/2e4e9ef1-d903-46c5-8ed0-c3963df62d53.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Nữ Trơn Tay Dài',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nữ Trơn Tay Dài'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2209ASU2450802/3a9292ba-7887-4673-9f79-0abcd0b7356d.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Nữ Tay Dài Phối Bèo',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Nữ Tay Dài Phối Bèo'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2212ASUFMF1401/68d35d2c-2cff-454c-92ee-996ff819753f.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 209000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '23',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Áo Kiểu Phối Viền Bèo Tà Xéo',
                'slug_san_pham'           => Str::slug('Áo Kiểu Phối Viền Bèo Tà Xéo'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2208AKUFMF0201/a0b33aa1-733a-4caa-b2e9-54f11084af3f.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Kiểu Cổ Tròn Đính Nơ',
                'slug_san_pham'           => Str::slug('Áo Kiểu Cổ Tròn Đính Nơ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2302AKUFMF1501/11256b22-2d1a-43e0-bb79-ca01dea3973e.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 149000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Áo Sơ Mi Kiểu Tay Phồng',
                'slug_san_pham'           => Str::slug('Áo Sơ Mi Kiểu Tay Phồng'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301ASUFMF0702/3633df2b-a430-4bb4-8b8f-f214092ada4e.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 175000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '24',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Jean Ống Suông Túi Hộp Nữ',
                'slug_san_pham'           => Str::slug('Quần Jean Ống Suông Túi Hộp Nữ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210BJU5361701/df0bb29a-8ae2-41b3-a352-8dcc30bfebe3.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 199000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Nữ Trơn Lai Cuốn',
                'slug_san_pham'           => Str::slug('Quần Jeans Nữ Trơn Lai Cuốn'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2204QJU5361661/13fbe258-4947-45f3-b13f-774eaee77ac2.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 239000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Jeans Skinny Nữ Cạp Cao',
                'slug_san_pham'           => Str::slug('Quần Jeans Skinny Nữ Cạp Cao'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2210QJU0621202/9f83901c-f870-48b2-b9bd-153266a26e73.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 265000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '25',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Lụa Ống Rộng Dây Đai',
                'slug_san_pham'           => Str::slug('Quần Lụa Ống Rộng Dây Đai'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211QBUFMF1801/271ba964-2e0d-4ce5-9cd7-13fd55dd465c.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 225000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Tây Baggy Gấu Lệch',
                'slug_san_pham'           => Str::slug('Quần Tây Baggy Gấu Lệch'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2109QBU5810707/82a30cd3-a369-470b-a0c1-56ee98ae13aa.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 145000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],
            [
                'ten_san_pham'            => 'Quần Tây Ống Rộng Xếp Ly',
                'slug_san_pham'           => Str::slug('Quần Tây Ống Rộng Xếp Ly'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2301QBUFMF0901/0080ac83-3dc9-4660-ab92-f6e0ef44aad3.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 269000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '26',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Baggy Kaki Ống Suông',
                'slug_san_pham'           => Str::slug('Quần Baggy Kaki Ống Suông'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2206QBU5362102/841b6bd4-8fe0-475e-bd62-089ef973193c.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 159000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '27',
                'trang_thai'              => '1',
            ],

            [
                'ten_san_pham'            => 'Quần Baggy Kaki Trơn Nữ',
                'slug_san_pham'           => Str::slug('Quần Baggy Kaki Trơn Nữ'),
                'hinh_anh'                => 'https://media-fmplus.cdn.vccloud.vn/uploads/products/2211QBU5360701/5f5953ec-0c94-4215-8460-2ff1dede564b.jpg',
                'mo_ta'                   => '- Phù hợp: Mặc đi học, đi làm, đi chơi.',
                'gia_ban'                 => 195000,
                'gia_khuyen_mai'          => null,
                'id_chuyen_muc'           => '27',
                'trang_thai'              => '1',
            ],



        ]);
    }
}
